---
title: "MODELOS LINEALES MIXTOS"
author: "Ruben Sanchez_Alvarado"
format: html
---

# Pasos para analisis de datos 
1. Crear mi diseño experimental --- modelo estadistico 
2. Colectar los datos 
3. Importar y verificar los factores 
4. Analisis de variancia 
5. Comparacion de medias 
6. Grafico 


# Librerias 

```{r}
library(tidyverse)
library(googlesheets4)
library(lme4)

```

# Cargar base de datos 

```{r}
url  <- "https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=172957346#gid=172957346"

gs <- url %>%
  as_sheets_id()

fb <- gs %>%
  range_read("fb") %>%
  mutate(across(1:bloque, ~as.factor(.)))

str(fb)

```
# Modelo 


$$  wue_{tuber} = \mu + bloque + riego + geno + riego*geno + e  $$ 

# Analisis de variancia 

```{r}
md <- lmer(formula = twue ~ 0 + (1|bloque) + riego*geno
           , data = fb)


anova(md)

library(car)

Anova(md)

```
# > Chatgpt completo 

```{r}
library(lme4)
library(emmeans)
library(multcomp)
```

```{r}
library(multcompView)
library(ggplot2)
library(dplyr)

# Modelo mixto
md <- lmer(twue ~ 0 + (1|bloque) + riego*geno, data = fb)

# ANOVA tipo II o III según interés
library(car)
Anova(md, type = 3)
```
















